name: Linter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Lint Code Base
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
